// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cards: dynamic(() => import("./Cards")),
  image: dynamic(() => import("./Image")),
  image_text: dynamic(() => import("./TextAndImage")),
  page_title: dynamic(() => import("./PageTitle")),
  richtext: dynamic(() => import("./Richtext")),
  separator: dynamic(() => import("./Separator")),
};
